# Generated by Django 6.0.1 on 2026-01-14 19:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmake',
            options={'ordering': ['name'], 'verbose_name': 'Car Make', 'verbose_name_plural': 'Car Makes'},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ['-year', 'car_make', 'name'], 'verbose_name': 'Car Model', 'verbose_name_plural': 'Car Models'},
        ),
        migrations.AlterField(
            model_name='carmake',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='car_make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='djangoapp.carmake'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='dealer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='type',
            field=models.CharField(choices=[('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('WAGON', 'Wagon'), ('COUPE', 'Coupe'), ('HATCHBACK', 'Hatchback'), ('TRUCK', 'Truck'), ('CONVERTIBLE', 'Convertible'), ('VAN', 'Van')], default='SEDAN', max_length=15),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2025), django.core.validators.MinValueValidator(2000)]),
        ),
    ]
